#!/usr/bin/env pwsh

# installs vscode extensions
# code --list-extensions

# vars
$extensions = @(
    'aaron-bond.better-comments'
    'albymor.increment-selection'
    'alefragnani.bookmarks'
    'azapi-vscode.azapi'
    'bencoleman.armview'
    'bierner.markdown-preview-github-styles'
    'davidanson.vscode-markdownlint'
    'dnut.rewrap-revived'
    'dqisme.sync-scroll'
    'eamodio.gitlens'
    'edwinhuish.better-comments-next'
    'emilast.logfilehighlighter'
    'esbenp.prettier-vscode'
    'foxundermoon.shell-format'
    'github.copilot'
    'github.copilot-chat'
    'github.vscode-github-actions'
    'gitlab.gitlab-workflow'
    'grapecity.gc-excelviewer'
    'gruntfuggly.todo-tree'
    'hashicorp.hcl'
    'hashicorp.terraform'
    'hediet.vscode-drawio'
    'humao.rest-client'
    'janisdd.vscode-edit-csv'
    'jetmartin.bats'
    'johnpapa.vscode-peacock'
    'mark-wiemer.vscode-autohotkey-plus-plus'
    'marp-team.marp-vscode'
    'mechatroner.rainbow-csv'
    'mhutchie.git-graph'
    'ms-azure-devops.azure-pipelines'
    'ms-azuretools.vscode-azurefunctions'
    'ms-azuretools.vscode-azureresourcegroups'
    'ms-azuretools.vscode-bicep'
    'ms-azuretools.vscode-cosmosdb'
    'ms-azuretools.vscode-docker'
    'ms-dotnettools.vscode-dotnet-runtime'
    'ms-kubernetes-tools.vscode-aks-tools'
    'ms-kubernetes-tools.vscode-kubernetes-tools'
    'ms-python.black-formatter'
    'ms-python.debugpy'
    'ms-python.isort'
    'ms-python.python'
    'ms-python.vscode-pylance'
    'ms-toolsai.datawrangler'
    'ms-toolsai.jupyter'
    'ms-toolsai.jupyter-keymap'
    'ms-toolsai.jupyter-renderers'
    'ms-toolsai.vscode-jupyter-cell-tags'
    'ms-toolsai.vscode-jupyter-slideshow'
    'ms-vscode-remote.remote-containers'
    'ms-vscode-remote.remote-ssh'
    'ms-vscode-remote.remote-ssh-edit'
    'ms-vscode-remote.remote-wsl'
    'ms-vscode-remote.vscode-remote-extensionpack'
    'ms-vscode.azurecli'
    'ms-vscode.powershell'
    'ms-vscode.remote-explorer'
    'ms-vscode.remote-server'
    'ms-vscode.vscode-speech'
    'msazurermtools.azurerm-vscode-tools'
    'oderwat.indent-rainbow'
    'pspester.pester-test'
    'qcz.text-power-tools'
    'rangav.vscode-thunder-client'
    'redhat.ansible'
    'redhat.vscode-commons'
    'redhat.vscode-xml'
    'redhat.vscode-yaml'
    'remisa.shellman'
    'richie5um2.vscode-sort-json'
    'rogalmic.bash-debug'
    'rosshamish.kuskus-kusto-syntax-highlighting'
    'shanoor.vscode-nginx'
    'sidneys1.gitconfig'
    'streetsidesoftware.code-spell-checker'
    'sztheory.vscode-packer-powertools'
    'tamasfe.even-better-toml'
    'timonwong.shellcheck'
    'tyriar.shell-launcher'
    'usernamehw.errorlens'
    'vscode-icons-team.vscode-icons'
    'wengerk.highlight-bad-chars'
    'william-voyek.vscode-nginx'
    'yzhang.markdown-all-in-one'
    'ziyasal.vscode-open-in-github'
)

# install vscode extensions
foreach ($extension in $extensions) {
    Write-Host "Installing $extension..."
    cursor --install-extension $extension
}
